services:
  api:
    build: ./apps/api
    restart: unless-stopped
    env_file:
      - ./.env.api
    environment:
      MONGO_URI: ${MONGO_URI:-mongodb+srv://erenasik1211_db_user:R4RSDeFPjeSXxB10@telegramtodo.gnsvcdl.mongodb.net/TelegramToDo?retryWrites=true&w=majority}
    ports:
      - "8990:8990"

  bot:
    build: ./apps/bot
    restart: unless-stopped
    env_file:
      - ./.env.bot
    environment:
      API_BASE_URL: http://api:8990
      ALLOWED_BOT_ID: 6285996403
    depends_on:
      - api

  web:
    build: ./apps/web
    restart: unless-stopped
    env_file:
      - ./.env.web
    environment:
      VITE_API_BASE_URL: http://77.37.54.190:8990
    ports:
      - "5173:5173"
    depends_on:
      - api
